library(dplyr)
library(tidyr)
library(bslib)
library(shinyjs)
library(shiny)
library(htmlwidgets)
library(DT)
library(data.table)
library(leaflet)
library(htmltools)
library(stringr)
library(shinycssloaders)

source("module/map_module.R")
source("module/map_module2.R")
source("module/process_map_data.R")
source("module/project_info.R")

data_dt <- readRDS("data/nuforc_reports_cleaned.rds") %>% as.data.table()