library(dplyr)
library(tidyr)
library(bslib)
library(shinyjs)
library(shiny)
library(shinyWidgets)
library(waiter)
library(htmlwidgets)
library(DT)
library(data.table)
library(leaflet)
library(htmltools)
library(stringr)
library(shinycssloaders)

source("modules/map_module.R")
source("modules/home_module.R")
source("modules/about_me.R")
source("modules/media_module.R")
source("modules/process_map_data.R")
data_dt <- readRDS("data/nuforc_reports_cleaned.rds") %>% as.data.table()